[tools]
postshot = "C:\\Program Files\\Jawset Postshot"
lichtfeld_studio = "C:\\Program Files\\LichtFeld-Studio"
splat_transform = "splat-transform"
supersplat_url = "https://superspl.at/editor"

[colmap_clean]
outlier_threshold_auto = true
outlier_threshold_fixed = 100.0
outlier_percentile = 0.99
outlier_multiplier = 2.5
kdtree_threshold = 0.001
coordinate_transform = [
    1,
    0,
    0,
    0,
    0,
    -1,
    0,
    1,
    0,
]

[postshot]
profile = "Splat3"
downsample = true
max_image_size = 3840
anti_aliasing = false
create_sky_model = false
train_steps_limit = 0           # 0 = auto (Postshot computes from image count)
login = ""
password = ""

[lichtfeld]
strategy = "mcmc"
iterations = 30000

[bunny]
storage_zone = "splatpipe"
storage_password = "9684d80c-c7ee-43d7-b4480cd12b7e-3ea6-40de"
cdn_url = "https://splatpipe-cdn.b-cdn.net"

[paths]
projects_root = "H:\\001_ProjectCache\\660 Drone\\_Photogrammetry"
